apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
spec:
  selector:
    matchLabels:
      run: classic-elb
  replicas: 1
  template:
    metadata:
      labels:
        run: classic-elb
    spec:
      containers:
        - name: hellonode
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP